#! /usr/bin/env python3


import sys
import csv

# Requires package geoip2fast from PyPi, providing access to GeoLite2
# data from MaxMind
from geoip2fast import GeoIP2Fast


class KorpLogIPAdder(object):

    def __init__(self):
        pass

    def process_log(self, args):
        if len(args) > 0:
            for fname in args:
                with open(fname, 'r') as f:
                    self._process_log(f)
        else:
            self._process_log(sys.stdin)

    def _process_log(self, stream):
        csv.field_size_limit(int(1e7))
        log_reader = csv.DictReader(stream, delimiter='\t',
                                    quoting=csv.QUOTE_NONE)
        in_fields = log_reader.fieldnames
        ip_fieldnr = in_fields.index('ip')
        out_fields = [field for field in in_fields]
        out_fields.insert(ip_fieldnr + 1, 'ip_country')
        sys.stdout.write('\t'.join(out_fields) + '\n')
        out_writer = csv.DictWriter(sys.stdout, out_fields, delimiter='\t',
                                    quoting=csv.QUOTE_NONE,
                                    extrasaction='ignore')
        geolite2 = GeoIP2Fast()
        for fields in log_reader:
            try:
                ip_info = geolite2.lookup(fields['ip'])
                country = ip_info.country_code
                if country == '--':
                    country = '-'
            except ValueError:
                country = '-'
            fields['ip_country'] = country
            out_writer.writerow(fields)


def main():
    log_processor = KorpLogIPAdder()
    log_processor.process_log(sys.argv[1:])


if __name__ == '__main__':
    main()
